INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'vidal.hartmann',
        'Karli',
        'Lemke',
        '$2y$10$23W/cTUyuO0iLZ.ONpaJ8eY.rjYztR89wk70sNZ5yB7oDnehxw6Hq',
        '95667789',
        'haag.shaun@hotmail.com',
        '2016-05-25 10:25:26',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'blick.silas',
        'Fabian',
        'Willms',
        '$2y$10$C/hb2gcCbiTq.N5mZRWup.OO/PYJpBn6NhV2L84lg8nXGLRSbpkTO',
        '60348262',
        'king.lucie@hotmail.com',
        '2008-05-07 06:53:46',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'gottlieb.franco',
        'Thalia',
        'Friesen',
        '$2y$10$UEFVZ1Jc/./3lCRcpJO2xuB0EAINv1E5i1J56pwK1FfDVC18Ybkne',
        '92814387',
        'bessie.hammes@hotmail.com',
        '2009-10-07 05:10:44',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'sincere78',
        'Tristian',
        'Tremblay',
        '$2y$10$Nh5naeo63E.ZpD7ZofX6dOVhNjLfbPUubMUx.gn4Lh0kGQXHotLpO',
        '84169210',
        'johnpaul.marvin@dare.com',
        '2008-07-03 02:25:08',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'jevon.stracke',
        'Kaylin',
        'Mitchell',
        '$2y$10$1wWmf8VWa6g2WneTnhF6Hupw0Re690B8gagYvVwM/5P767DiWDdIG',
        '90573926',
        'lwillms@stokes.com',
        '2009-08-21 15:19:32',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'gerson.heathcote',
        'Torrance',
        'Beer',
        '$2y$10$jBadh5.BfMal3lKa/zzE.eih4MTPOSHiEmdxNAuwYws5zePCC7aEC',
        '89406935',
        'angelina11@yahoo.com',
        '2015-01-28 20:04:01',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'gibson.amparo',
        'Earl',
        'Nolan',
        '$2y$10$JuAfvEgZl4mhEsoLobdQEuUDzyROll9t9PQ.t4VmZCdDwu.svqwv2',
        '69620668',
        'miller.germaine@boyle.biz',
        '2012-07-30 17:56:05',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'elvie.dicki',
        'Jacynthe',
        'Farrell',
        '$2y$10$p/qrNbjsXmKzC2xUa/ogM.IOopg5/cZu22Wp26sVnWjG8Sl2MBgCW',
        '92313725',
        'pietro62@yahoo.com',
        '2016-07-04 11:54:34',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'bradtke.albina',
        'Ambrose',
        'Marks',
        '$2y$10$pE5/5RMBZnzeEIAA.QSkreTZkJmT5GziJm1h5vW6u3m/iSQ2/HL8O',
        '81754432',
        'bailee70@hotmail.com',
        '2012-08-06 06:09:03',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'isaiah.gleason',
        'Emily',
        'Kunde',
        '$2y$10$roWzvC2zQxegtU6KgZZTXuvuacULqveu48Yhx6uLOOvGev.I6UKrW',
        '63476875',
        'rod.orn@yahoo.com',
        '2009-05-10 18:38:21',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'gutkowski.gussie',
        'Geraldine',
        'Abbott',
        '$2y$10$BDDArA49oN.GHrH64g9Xv.z7Y/VOSQI.X2xgj1Y9Ov5WLTSzl1uKi',
        '99929081',
        'alessia01@kuphal.com',
        '2011-08-09 03:23:42',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'wava20',
        'Floyd',
        'White',
        '$2y$10$vftCxbaWNF.TjQbE3NFaM.Di3lH6FFbLOim/nAJyUg9jOTuHVjuYm',
        '91340191',
        'bmccullough@yahoo.com',
        '2008-04-03 08:47:54',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'grace10',
        'Dorthy',
        'Dare',
        '$2y$10$Sbjy/BxnCa0oWN9D3TEOEeZm/tSje00akwPgm8uVJY5j26Iq07Vzi',
        '88768960',
        'kayli08@hotmail.com',
        '2015-11-24 14:17:58',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'kozey.alayna',
        'Delphine',
        'Russel',
        '$2y$10$15Hrj5NheJmLMfZTeG38fOm97QrmCR.DL9vsoGhfuNDVMRbM0vv5y',
        '85693362',
        'buckridge.asia@medhurst.com',
        '2015-09-17 17:05:36',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'chaya70',
        'Monserrat',
        'Marks',
        '$2y$10$XADhZjcnF0y87I62anxLrOf7gUSkjiG3T7I242bMfMHlDEHNsIgb6',
        '93256594',
        'kylee66@gmail.com',
        '2016-07-30 03:01:16',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'ruecker.chanelle',
        'Rachelle',
        'Upton',
        '$2y$10$sATEfEvMBPTeyHMGgeteXOlKpwQ47L0gLGGOTlRO1HWsvgcZrVq8.',
        '66024286',
        'evonrueden@dietrich.net',
        '2012-09-24 00:27:52',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'antone84',
        'Travon',
        'Vandervort',
        '$2y$10$kckdVc6AByJa5shTmyaGV.A1DzbfhpTl0IsszrTXN45MMFTbruh0u',
        '97866674',
        'williamson.richard@abshire.info',
        '2010-07-24 08:16:10',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'arnold.muller',
        'Eleanora',
        'Kris',
        '$2y$10$9kYWEckfPHYa7FzQiEAoVuZFZRkd98bf6TFvytNCH5uDVIaId/7fO',
        '92471551',
        'hintz.saul@hotmail.com',
        '2015-03-22 23:06:46',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'lemuel.casper',
        'Maude',
        'Altenwerth',
        '$2y$10$3rJU8IzM3vj6h7xAsTDY9.lZqBcUfqVkosuQinyJdxijQHh5ViRMe',
        '83776124',
        'quigley.russel@gmail.com',
        '2013-03-05 14:07:56',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'sbrown',
        'Haylee',
        'Kerluke',
        '$2y$10$80FHgWNvXISa4.XO3invr.W9p3fugVBNV1Ax0hd8HJEyKrxToMQIm',
        '65014085',
        'waelchi.roberto@gmail.com',
        '2014-03-02 16:23:43',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'kwillms',
        'Jarrod',
        'Sanford',
        '$2y$10$lU7kasZ5ghLxn.vNyulbbuGOo63b.5EnePXl.485DW7Pg1sbWemie',
        '99356578',
        'antonietta.gorczany@labadie.com',
        '2010-01-19 14:09:17',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'mark18',
        'Adrien',
        'Zemlak',
        '$2y$10$XfQXF1iSR6RrI5L0S0qP3OB3FztNlLXUIUDwLZP.iJrETngmGJEye',
        '63964694',
        'walsh.lexi@gmail.com',
        '2010-09-21 11:50:00',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'rhiannon.bergnaum',
        'Isidro',
        'Fritsch',
        '$2y$10$kVIanlFeNDAh//aE9Xy1gO9Ii3EctXGzTP/OEWZY3D1md4Bc9AIC6',
        '96619765',
        'leslie82@yahoo.com',
        '2011-03-02 06:01:17',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'durgan.benedict',
        'Mack',
        'Wyman',
        '$2y$10$2bRH1GbyxV91Lib3CUwfXO43f5cy7bWXtPlVc.fZCpoIz.DcVJm/S',
        '86037168',
        'nmohr@hotmail.com',
        '2008-01-04 11:51:05',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'colby.kohler',
        'Isac',
        'Mohr',
        '$2y$10$/VVV4u4yGToLeZgSdeoybeBxz.23jKufA5xI5ZxPQf5snZ.Ti7PCu',
        '66381465',
        'leonardo.moore@yahoo.com',
        '2015-09-18 23:27:31',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'agerhold',
        'Alexandro',
        'Koelpin',
        '$2y$10$6FcHGZZfxnUFoLx4n4QFd.0QQOE91akNMkLD5YzZD4qSQpq/PUrD6',
        '88330518',
        'nschmitt@auer.biz',
        '2011-04-27 22:54:07',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'gia.windler',
        'Aniyah',
        'Turner',
        '$2y$10$CjUz5EUajOpDR0VoTxPclesAUGbLgOePTQ3T2wqWFRcrv3XtpzZmG',
        '81432770',
        'alan.lehner@bradtke.org',
        '2008-03-07 06:27:43',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'arielle.frami',
        'Dayton',
        'Baumbach',
        '$2y$10$YLZR5TvcmSDjTU8Up4JOyOMALquBFpA.oD8HFFjp.4jZ3Dj0plkI.',
        '67182762',
        'hamill.kaela@hotmail.com',
        '2009-07-14 10:14:29',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'ykulas',
        'Odessa',
        'Hodkiewicz',
        '$2y$10$ByeD.ENqnfbevWJWwfNZtuAJacNQopQSbEPzNlMs6dQUqigpuXTzm',
        '69105780',
        'yfeest@yahoo.com',
        '2014-08-03 18:03:47',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'cory28',
        'Isaias',
        'Hilpert',
        '$2y$10$1Bl9Ptp9GLqxZipcXtxapuMgZGGsam6V2/pzg35KIdknePysyJazi',
        '88712086',
        'maggio.wilhelm@johns.com',
        '2010-01-30 01:56:28',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'amina00',
        'Aida',
        'Stehr',
        '$2y$10$dXBXtzhxzzG5q4C2lTEFfO/u/WKm0RwcFigWSAKbkuNbBqr3n/fvC',
        '87177396',
        'katelynn20@yahoo.com',
        '2012-01-12 07:27:37',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'abauch',
        'Jonathon',
        'Blanda',
        '$2y$10$KOj1KEZuUY89ulzMu/9Nnex.4Q7Ofrt6KCWIOhh4TZ.CEAxAGR9AK',
        '81433545',
        'romaine86@kutch.com',
        '2013-02-24 03:54:59',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'lebsack.mustafa',
        'Xzavier',
        'Krajcik',
        '$2y$10$MgUq4y26Lo8o18ncJVJ66uGhgepB1n4IApBb34EnxLnIc4tJCX13y',
        '64790021',
        'summer41@gmail.com',
        '2010-01-23 15:14:16',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'lisa59',
        'Della',
        'Langosh',
        '$2y$10$PwCdZYd0mvOxROkoC97qeu9Mj1kzYN2/faIwtltq4q0XyTHTEczaW',
        '87570941',
        'unolan@lemke.com',
        '2007-11-04 19:43:21',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'barbara82',
        'Sydney',
        'West',
        '$2y$10$FJU0BiCeHhd5SZOehqDUx.A.tyhs2zVytcbF.xYqyHZ0/Gcm.r.1e',
        '66405272',
        'hwatsica@yahoo.com',
        '2015-05-17 12:09:29',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'layla.krajcik',
        'Greta',
        'Morar',
        '$2y$10$.7S9XtGueE78tW3ksledJ.HVkGDe.xJ6eEUM8eKU7bopge/bYjRm.',
        '92686449',
        'tina98@gmail.com',
        '2015-12-09 04:13:56',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'wolff.trudie',
        'Kian',
        'Dach',
        '$2y$10$uYLU9yf5Q3B2mCa9PfsvD.kPSEGQuCkp.xgUANc6pcdG1wa3sWzGa',
        '80872300',
        'vicente.rowe@hotmail.com',
        '2010-05-01 15:22:55',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'kristofer24',
        'Dixie',
        'Stiedemann',
        '$2y$10$l0oQtbgwruo5ZP4ny1IJuOshbjidNpWCEopF4jcHTT7RP2WhjTFzO',
        '96162293',
        'khalid30@yahoo.com',
        '2014-09-03 07:20:31',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'rbahringer',
        'Carolina',
        'Will',
        '$2y$10$XJn3Nk7AlnwE8cJM4BSByu6.vK8IhjGZzl..hLwgDow3LyISTxWI.',
        '98221698',
        'eula.kuphal@johnston.info',
        '2011-04-03 06:24:54',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'boehm.jarrell',
        'Brittany',
        'Weber',
        '$2y$10$8vwjhywhPPwDM6KeddCnkOrZTcK9Hd/m7jvRThy7.rZ2.9BSil7Hu',
        '93549176',
        'justice.marquardt@ondricka.com',
        '2010-10-09 20:13:45',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'geovanni32',
        'Haley',
        'Runolfsdottir',
        '$2y$10$hPMpxDjXLOoBinANDKtbC.fS2NP35nvpo2sGJPU/SBEyubqyat8Hy',
        '82358138',
        'marjorie.nitzsche@wolff.com',
        '2009-06-27 15:42:05',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'roman.kohler',
        'Nikolas',
        'Nitzsche',
        '$2y$10$D.dGXPpZ.155CKomoZvvnuoAjNHfkIexDoS1WW14RLnrSd4NE0ul.',
        '62265320',
        'legros.karelle@hyatt.com',
        '2009-01-21 20:20:29',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'dicki.hugh',
        'Catalina',
        'Cartwright',
        '$2y$10$PAoUqEgEEikm635/JRJC.uazWghf/1OPEOxMfM6vtSxB8kZ6gL0be',
        '87347145',
        'hilton13@schinner.com',
        '2015-05-19 13:27:35',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'retta.thiel',
        'Magdalena',
        'Lang',
        '$2y$10$DAcdOr1g9Ec5z843lrswoeanJlCmF1TrEaR29eOQE8jtUfcMLBvA2',
        '63390921',
        'hubert.wisozk@goodwin.com',
        '2013-03-13 05:17:03',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'roberts.lionel',
        'Lilian',
        'Smitham',
        '$2y$10$Zs.HKvZWtQCasrFhBYqOXOjXOPMAopGqS.kV9wDuGDK/2Avh5LjGS',
        '98948852',
        'gusikowski.karl@rosenbaum.com',
        '2009-09-22 09:47:04',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'felipe.powlowski',
        'Lessie',
        'Howe',
        '$2y$10$7kwL8g/Ej4pPCh/ZquygHekpzTQkNipBJIt65LZ837g8Hj/XAy0aS',
        '94795087',
        'rempel.christina@yahoo.com',
        '2012-01-26 22:49:10',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'ila.keebler',
        'Marie',
        'Witting',
        '$2y$10$wYvN/RnbCmw.PhU0Wjejsu8mSwaqVOKEkK8aVYD9OpFfcwhjKUKqG',
        '94121643',
        'inicolas@bednar.com',
        '2009-08-18 02:37:29',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'lebsack.herta',
        'Jayde',
        'Klein',
        '$2y$10$Fy.3HlvG40j3GHKt5GOWAuD5pHkMUNQsd3TQReyyJsVDy3dPN1SmG',
        '97026335',
        'ella.brekke@willms.com',
        '2009-06-28 16:33:31',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'rsimonis',
        'Chelsie',
        'Hettinger',
        '$2y$10$GFdqA1zqCLTO94dLFOX59emZEMn3m6VtkzD4jq0Mtq6qLgxu1bKEi',
        '66611299',
        'gaylord.brayan@hotmail.com',
        '2008-11-24 16:16:05',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'giovanny.huel',
        'Melyssa',
        'Bailey',
        '$2y$10$C.c8lR6NLz4LYv9cBv.0DOTp91CNDt//wJLtLi32EPBQ0wh1GfTJy',
        '86601283',
        'halvorson.kelvin@yahoo.com',
        '2009-12-04 22:56:56',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'watsica.pierre',
        'Tyrel',
        'Kessler',
        '$2y$10$/8zViZsREMLam9g4WzKs4uTN.MwuiTm7DRDtvSkunuZ8GoCsamPpi',
        '92437777',
        'ddouglas@mertz.com',
        '2011-08-06 00:32:53',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'gheller',
        'Anabelle',
        'Nicolas',
        '$2y$10$eQ6KdLlmokBCdrkTWosuVeeS35zIteNw8D2nILKHwHOVttoG99Gu2',
        '85077166',
        'gorczany.karli@bradtke.info',
        '2013-11-01 07:24:11',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'vwalter',
        'Dorris',
        'Ullrich',
        '$2y$10$qPJ7JdSzHB72c35byAaB7Oe7o0zghFlRVCT5vHWyS7agPY68Lclwu',
        '95760103',
        'swift.liliana@gmail.com',
        '2011-04-14 22:16:59',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'littel.kennedy',
        'Caleb',
        'Howell',
        '$2y$10$kXPSbpVbeQ/KzC24WhyMMedMlHnKB8STHjFqa8io3uewvB2chb77W',
        '60210367',
        'vella.vandervort@gmail.com',
        '2015-05-10 01:08:22',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'rath.earlene',
        'Nikko',
        'Kautzer',
        '$2y$10$yY0vVDNnYrCalHifS3IVseDsxU3c1onnpxRUcpENP5gm4ZYZsDOnK',
        '83797343',
        'ava.renner@hettinger.net',
        '2016-01-05 15:03:39',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'macejkovic.derek',
        'Beth',
        'Ruecker',
        '$2y$10$5dW.JrRsZtClIeFHASTduekJJ.Xai.7iJhgWxMwo.xbOhTWenTHJa',
        '94993379',
        'milford.rau@kihn.com',
        '2017-01-01 06:19:50',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'jean.medhurst',
        'Florence',
        'Ziemann',
        '$2y$10$bxW3knUV0r/CgvgvZ27Dv.EBCB4pqaRFeGy36rn5O0rTU4c96Nd/m',
        '91734631',
        'geovanni40@yahoo.com',
        '2013-11-10 17:31:19',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'jhegmann',
        'Diego',
        'Baumbach',
        '$2y$10$keqUGdnrPDvWMmkVeA.8ROUCUXIrwfxL3.lOKAmQLwdfEIKk.G62u',
        '96764906',
        'connor16@hotmail.com',
        '2011-08-28 23:45:50',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'zboncak.alexis',
        'Candelario',
        'Jacobs',
        '$2y$10$z4HwSZx8MuO5GmGqX/0dbuiuoPdF54WgzZBAZRvHFqSTm1u7NkNfC',
        '99085511',
        'elisa33@hotmail.com',
        '2015-09-28 19:48:03',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'jewell71',
        'Daphne',
        'Rempel',
        '$2y$10$lY4SLlgAa/4haRTjEq/54.ZzqvnwSF6nxPP3WOrvqgWXkPlgvbAR.',
        '80831710',
        'rbuckridge@hermann.org',
        '2017-01-28 08:12:49',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'deckow.melba',
        'Darwin',
        'Zieme',
        '$2y$10$HZN4pWLSl/ODS10XvRayb.bauesK5ZewOchCwKU3gJ3aoVO.VMUBG',
        '95214687',
        'tmacejkovic@hotmail.com',
        '2009-03-25 11:17:32',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'cruickshank.kiana',
        'Antwon',
        'Thiel',
        '$2y$10$bHtdy6VyQyGP3Rfy3dqoMeyW3MiPOnUFX49S5YV9UNd9bDRj8hmce',
        '84768189',
        'novella.leuschke@gmail.com',
        '2009-09-09 14:27:00',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'amos56',
        'Crystel',
        'Gislason',
        '$2y$10$PGg9o6vpNgTr22JVeJxcT.4VWCDL/o8I3WkczkmnmIFZq1Qy.miwi',
        '85800641',
        'vwindler@halvorson.com',
        '2015-04-10 12:25:07',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'lucienne37',
        'Augustine',
        'Anderson',
        '$2y$10$Ruw3eZ/HV/DMfN0yV5n.Y.DBcE44k9m7Rzn4jKNOanIjd4PaGNPUO',
        '83686241',
        'acrist@mcdermott.org',
        '2016-07-12 15:00:16',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'mittie.rohan',
        'Abigale',
        'Altenwerth',
        '$2y$10$TEZHlpd6nvFr39IXshw7Gu/Wo9a.5iblY8jl32r4LAPCMK1AexU4i',
        '81194520',
        'german24@rempel.com',
        '2014-01-22 06:43:37',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'annie.stoltenberg',
        'Odie',
        'Feil',
        '$2y$10$6kZ8D7XLG9mrvL6roUv6oux3sLh/cSFevon0sqYLakuMQybGUjYba',
        '97731671',
        'hhansen@yahoo.com',
        '2008-02-21 15:40:47',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'gregoria80',
        'Nicholas',
        'Terry',
        '$2y$10$WZhaFwWx2vr7wqnoxYiLF.yP8fBbOit4FQdJpIoDVQYMzqljrnDGK',
        '60304792',
        'olindgren@hotmail.com',
        '2008-06-07 10:35:36',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'mariane.muller',
        'Glen',
        'Larkin',
        '$2y$10$L8KdLFne1XIDv//w2rvXBeD8yxFt9NL27g8Z/yvEXR3frJariUybG',
        '68497625',
        'ena.hodkiewicz@gmail.com',
        '2008-09-12 10:24:06',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'wiley.cremin',
        'Herminia',
        'VonRueden',
        '$2y$10$gf0hvY9xD.e44SZiwsXHsOSa.qnFhizEq6ubFvkRcwecSpPD6a8K2',
        '68820319',
        'leonardo.dach@hotmail.com',
        '2010-07-31 23:07:10',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'grempel',
        'Maxime',
        'Romaguera',
        '$2y$10$017Jk3lf72YQIZyTPiIqD.QVhbUl429iQ3CW/csg3hog3bM7Uyhh2',
        '96592988',
        'kconn@hotmail.com',
        '2016-07-13 23:07:28',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'sporer.yesenia',
        'Elza',
        'Brown',
        '$2y$10$.a74nZXz8FG0.4udQ2IlM.6751EOZGpDoCBZI3LGz8D4oVHtF78/y',
        '97962343',
        'carter.hand@hotmail.com',
        '2010-02-03 12:00:03',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'lklocko',
        'Cathrine',
        'Collier',
        '$2y$10$cyMfcJaVz4DvK9os1YiOT.1yvGqptfAvcDXTFnet4WZig57ztQrJm',
        '98879138',
        'dina35@hotmail.com',
        '2009-03-21 02:07:53',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'armstrong.daisy',
        'Lacey',
        'Davis',
        '$2y$10$Yfaqu8QkGb6h4ak1aGa9oeGRqymqGmiYQlErf.xi3V1Y5ujyENb.q',
        '62425981',
        'ada17@yahoo.com',
        '2015-09-24 18:59:23',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'boehm.kaleigh',
        'Caesar',
        'Wunsch',
        '$2y$10$0g73ouAHucfUcUbw7xPJeevJpBppEUAfN7kMAjPolAoI4eTD.KN2y',
        '86416595',
        'talia81@connelly.com',
        '2012-11-17 08:53:44',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'tremblay.eula',
        'Lazaro',
        'Langworth',
        '$2y$10$RPz.DWM6j7fWdU.L9f.4Gesx/kNKtLh3OHjlF8CNmJ5hb/wUGttcK',
        '96956223',
        'kylee.parker@dubuque.com',
        '2017-06-01 23:56:19',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'nmohr',
        'Chet',
        'Koelpin',
        '$2y$10$LDkRhtDzVfCwI.cPCvwvI.ptX1BXgHEgu9IbYAZ5nBZG4Fc6ZPpPe',
        '95166164',
        'demarcus.emmerich@gmail.com',
        '2012-09-15 13:44:49',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'hermann.triston',
        'Delilah',
        'Oberbrunner',
        '$2y$10$p3MzgUX3L4.eQFJiLIdSFO6TYusaNW0n4kZ0WSDTNRK3fUeTmMc6O',
        '63532041',
        'akerluke@hotmail.com',
        '2012-10-18 04:01:47',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'nheidenreich',
        'Dante',
        'Mohr',
        '$2y$10$qn5CK2q2X4F8ydQWeoHcpeg0xB/Pis8lthVrZf8yKWP.prqMhVPa2',
        '81315521',
        'kub.jacynthe@yahoo.com',
        '2013-03-26 16:24:28',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'kdenesik',
        'Hermann',
        'Cassin',
        '$2y$10$I9rcaIA5jQURx5TLuCWYF.Hl/F/5ipH5jLLopYameQUve9e2dSSpm',
        '91788528',
        'obie.hoeger@hotmail.com',
        '2009-12-11 19:24:12',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'crooks.lawrence',
        'Zita',
        'Wilderman',
        '$2y$10$9XPJiMHx6BBer1hK9R3kou/kGrDPVH4RX.Fkno2eLibcXQjtPRsXC',
        '89881475',
        'luciano83@quigley.com',
        '2014-11-01 14:32:32',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'christop.cummerata',
        'Orval',
        'Kunze',
        '$2y$10$/suP/3Tg3yFUCXO/kw.k0u7uCbRnN5N3O/mud23mI7MUqRzliAGZm',
        '82626433',
        'laila14@mayert.com',
        '2009-07-11 21:46:31',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'zieme.sim',
        'Mina',
        'Gleichner',
        '$2y$10$guy8l.CyfKJxvF5FimuKIuDnEs2OcrmTmwU/Ppq2Rn6EUWxqHw5eG',
        '87465497',
        'ryder.rippin@corkery.info',
        '2012-05-09 10:28:01',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'gottlieb.samanta',
        'Gus',
        'Macejkovic',
        '$2y$10$M3gHktBD9g/SRqlEQ7kRVOHQrUPdGZcQYdaWk.GHcABvkPaRGxB.W',
        '61539013',
        'ydaugherty@hotmail.com',
        '2013-07-18 09:13:55',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'uheidenreich',
        'Maxwell',
        'Runolfsdottir',
        '$2y$10$7Cj/bRNJ11u3GaTraoQTHeCIjbNP.XP5xtqz8skgLv8hIkJvLpXoS',
        '61536047',
        'zfeeney@hotmail.com',
        '2008-11-19 00:34:34',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'cwiza',
        'Linda',
        'Bechtelar',
        '$2y$10$JmTwsBywZd.VsYNc6Bcnwe3SBHHrcfj1j0KphrI45ZVRBQYh41gui',
        '83405767',
        'thaddeus98@jast.com',
        '2010-09-20 06:49:09',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'reichert.pearl',
        'Mateo',
        'Sipes',
        '$2y$10$RBPaBW7TET90fheeQxOAZe/KG8K7wsidK45gk4oso0saaT67Mw2o6',
        '96141950',
        'ubraun@gmail.com',
        '2009-05-22 15:42:48',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'powlowski.wiley',
        'Maiya',
        'Mann',
        '$2y$10$zNZQKhHkXmCQXLNfDv2uDuhx0M9LoBsJ7T5NhviT2yx3ISUJDD56a',
        '83245507',
        'qbarrows@effertz.com',
        '2013-10-05 16:59:16',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'xwolff',
        'Payton',
        'Bernier',
        '$2y$10$Wd9MYUZCP0WIi4Ym9KPfcuaLmuoXOmi43dtRA4WVwSo15IazxBv22',
        '99320274',
        'alysa54@gmail.com',
        '2015-03-27 13:58:47',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'milton67',
        'Rory',
        'Hammes',
        '$2y$10$p48qDFld3S9s1SrjoH7fKuyc2r5s9daSI.WGpSyGCZudhLcBwjbcq',
        '64468546',
        'obeer@yahoo.com',
        '2012-03-18 14:29:49',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'retta69',
        'Hassie',
        'Swaniawski',
        '$2y$10$MMgxYFwlflcBlrCtKCKex.cU9Efk2TrLBimoH.Ts02mkhqnocqlB6',
        '92333979',
        'pjenkins@lebsack.com',
        '2014-03-05 10:06:04',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'timmothy43',
        'Cale',
        'Reichel',
        '$2y$10$snXkiVZAY0IrPtgERjWaUOjiFm4mtro051kGCxPvaY/yo7dWIFDSy',
        '87517121',
        'shayne52@gmail.com',
        '2008-06-18 02:52:33',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'bode.alyce',
        'Kasandra',
        'Schinner',
        '$2y$10$XMuE8FWo7eD0dk04Q5cPr.XSq8rBHk/edsoJssxQRYhl7gah.d3Na',
        '80727175',
        'justyn.mcglynn@hotmail.com',
        '2011-05-17 05:11:31',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'guillermo53',
        'Theresia',
        'Leuschke',
        '$2y$10$X0FYjpcH.8.9dAzODr9EXevVWcVo8D0BTpbqo7DLZR43l/DycPoQO',
        '98373711',
        'vtoy@gmail.com',
        '2011-05-06 18:34:41',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'corkery.madonna',
        'Jay',
        'Koch',
        '$2y$10$1xF3.ILNK9WC2VU05D3prOq//FYenFCWX7YRIrKhjEN.bsu.VAXkK',
        '94508306',
        'akunde@hotmail.com',
        '2012-08-09 22:00:08',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'gorczany.misty',
        'Caitlyn',
        'Predovic',
        '$2y$10$5qPXSgt47YTxDP5rI1CZH.I9d1.YdAX6d/Z9i2B/oS.UwtM79i4Ge',
        '83842493',
        'magali.schiller@yahoo.com',
        '2011-10-26 07:31:29',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'irma06',
        'Garrick',
        'Lind',
        '$2y$10$9d9LHBmbwI/mV0/lXhWHOeqgyjTkXI3mEIfVrO5brfMqjIwc0Cnk.',
        '69988612',
        'joesph05@gmail.com',
        '2013-08-22 15:05:57',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'monique.greenholt',
        'Lilyan',
        'Yost',
        '$2y$10$qMhS9IQauWzNZFJkH45vsOeHMo9qLjp3.UZ26rQBpnD.JIR9uOL22',
        '65585149',
        'felicita.hills@yahoo.com',
        '2009-05-26 18:09:08',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'ebernhard',
        'Marques',
        'Buckridge',
        '$2y$10$8wn.4Jt6v6WKPDx2Jd0Nn.Jf9P1L3uuk3dpMQX5S82poTQXl.6AxO',
        '86698993',
        'herman.terrence@hotmail.com',
        '2009-09-23 23:02:21',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'verona90',
        'Hassan',
        'Dicki',
        '$2y$10$DVvWJSSnNqTGARrasPZTu.BJ/Z/Hx3Esjeq18kXdFT.s/7TeTrPpC',
        '84604471',
        'rosalyn28@gmail.com',
        '2013-05-15 06:09:45',
        '',
        '',
        'User'
    );INSERT INTO User
    (`username`,
      `first_name`,
      `last_name`,
      `password_hash`,
      `contact`,
      `email`,
      `created_at`,
      `updated_at`,
      `deleted_at`,
      `user_type`)
      VALUES (
        'qbaumbach',
        'Emery',
        'White',
        '$2y$10$KI9bS47ix3yRotsrPg9M3u/7xw7MZ4KoCJsZH7uEqzNNEx5tM0czy',
        '90202449',
        'constance19@yahoo.com',
        '2013-07-08 03:54:18',
        '',
        '',
        'User'
    );