INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Clinical Laboratory Technician',
      'Ut asperiores ad aut enim hic soluta natus quis. Earum nostrum corrupti sit ratione. Aut quam qui amet eum recusandae minus. Vero voluptate doloremque et vel officiis porro.',
      '2007-12-29 11:13:04',
      '2007-12-29 11:13:04',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '27',
      '75',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Computer Science Teacher',
      'A voluptas quis amet quia ut non. Aut aut omnis nesciunt quis molestiae est.',
      '2009-06-16 09:07:13',
      '2009-06-16 09:07:13',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '26',
      '104',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Maintenance and Repair Worker',
      'Ut quasi aut earum. Aut est est beatae cumque perferendis. Dolores sit iusto et saepe consectetur.',
      '2011-07-16 13:29:18',
      '2011-07-16 13:29:18',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '25',
      '115',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Mail Machine Operator',
      'Repellendus molestias repellat numquam dolor ut sed. Doloribus iusto ad blanditiis iste reprehenderit id et accusantium. Qui provident dolores facilis odit repellendus. Non vel eos quibusdam nobis excepturi.',
      '2013-12-14 19:26:16',
      '2013-12-14 19:26:16',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '26',
      '82',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Short Order Cook',
      'Eum et harum aut reprehenderit nisi nam molestias. Nesciunt illo repellat est quia. Suscipit voluptatem vel vero ut ducimus est. Esse et eos voluptatem aut.',
      '2009-10-04 22:11:16',
      '2009-10-04 22:11:16',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '11',
      '57',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Electrical Engineer',
      'Et aut rerum qui molestias cupiditate. Libero consequuntur laudantium enim est et vitae laboriosam sed. Voluptatibus iste voluptates fugiat et et. Aliquid numquam consequuntur explicabo non.',
      '2008-08-28 15:59:24',
      '2008-08-28 15:59:24',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '5',
      '107',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Hairdresser OR Cosmetologist',
      'Fugiat sunt molestias sint blanditiis doloribus inventore animi. Est blanditiis voluptates voluptates similique soluta possimus assumenda. Facere voluptatem facilis rerum nihil necessitatibus temporibus. Ducimus doloribus animi aut id eveniet omnis voluptatibus neque.',
      '2011-09-27 17:25:25',
      '2011-09-27 17:25:25',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '34',
      '96',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Online Marketing Analyst',
      'Non cupiditate veniam ut voluptatem. Optio quo voluptas quo voluptatem similique maxime architecto. Id itaque aut magnam. Quia dolores natus voluptatem quia. Et consequatur et totam unde soluta.',
      '2013-03-09 23:02:40',
      '2013-03-09 23:02:40',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '37',
      '116',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Painter and Illustrator',
      'Aut odio quia delectus et totam. Neque id cupiditate dolores reiciendis eum animi at. Fugiat reiciendis facere consectetur ipsam libero. Quam sapiente blanditiis facere ea.',
      '2013-05-09 22:46:20',
      '2013-05-09 22:46:20',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '15',
      '67',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Interpreter OR Translator',
      'Eaque voluptatem sequi reiciendis reiciendis nisi eaque occaecati. Fugit distinctio quasi modi expedita asperiores quis ut. Fugiat praesentium et voluptatum repudiandae quae cupiditate. Qui dolor aut est delectus.',
      '2014-12-28 02:56:26',
      '2014-12-28 02:56:26',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '27',
      '53',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Orthotist OR Prosthetist',
      'Rem assumenda laboriosam repudiandae velit adipisci qui. Explicabo vel esse nostrum et. Eum ut architecto ut rerum sed eaque dolor. Eum laboriosam eos deleniti quia. Eos blanditiis animi nam enim sunt.',
      '2010-11-01 09:28:19',
      '2010-11-01 09:28:19',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '9',
      '103',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Network Admin OR Computer Systems Administrator',
      'Molestiae similique doloremque et nam beatae ut. Cumque ad dolor eos sit dolores. Laborum accusantium at ut tenetur perspiciatis ut officia.',
      '2010-08-27 19:01:15',
      '2010-08-27 19:01:15',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '32',
      '97',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Team Assembler',
      'Ipsum a corrupti nisi quo. Architecto ut dolorem animi iste deserunt eveniet sunt. Quibusdam minima ad dolores voluptatem.',
      '2011-04-09 19:18:25',
      '2011-04-09 19:18:25',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '17',
      '88',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Director Religious Activities',
      'Molestiae minima sit eos modi. Tempora consequatur voluptas quo. Animi temporibus inventore voluptatem cum enim. Qui natus iusto aspernatur provident necessitatibus aut rerum.',
      '2009-05-24 16:47:36',
      '2009-05-24 16:47:36',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '38',
      '63',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Alteration Tailor',
      'Minima recusandae error a nostrum est eligendi. Sed vel sunt beatae beatae corrupti. Velit ratione repudiandae tenetur est aliquam fugiat. Voluptatum ipsam qui id fugit nostrum similique quo.',
      '2017-03-07 16:03:56',
      '2017-03-07 16:03:56',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '12',
      '85',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Metal Molding Operator',
      'At aut iusto placeat et possimus aut velit. Rerum et consectetur ut incidunt. Repudiandae nihil et voluptas enim facere non. Beatae porro similique ipsam velit.',
      '2013-10-16 16:53:16',
      '2013-10-16 16:53:16',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '29',
      '71',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Production Helper',
      'Assumenda sint illum illum qui quis excepturi. Exercitationem quis consequatur aut hic dolor at. Neque ex qui sed omnis et molestiae voluptatem eum.',
      '2008-07-06 07:46:25',
      '2008-07-06 07:46:25',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '36',
      '105',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Aircraft Launch and Recovery Officer',
      'Velit sed necessitatibus illo assumenda omnis. Quibusdam nisi autem repudiandae. Iusto sapiente est veniam eos qui aut laudantium. Enim soluta qui sit esse.',
      '2010-09-03 05:48:49',
      '2010-09-03 05:48:49',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '5',
      '77',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Fire-Prevention Engineer',
      'Voluptatem perspiciatis quis earum consequatur. Excepturi dignissimos sit enim est in. Debitis id maxime unde reiciendis et. Ea assumenda id nemo. Hic et vero iure dolores enim temporibus.',
      '2015-04-01 03:02:19',
      '2015-04-01 03:02:19',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '28',
      '66',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Shoe Machine Operators',
      'Maiores non ipsa quod ad eum aperiam. Eaque occaecati voluptas natus voluptatem sed veniam sint. Modi sed quas laboriosam aut. Id consequatur vel asperiores quo.',
      '2009-07-16 13:46:13',
      '2009-07-16 13:46:13',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '12',
      '58',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Mining Machine Operator',
      'Est consequuntur omnis saepe ipsum consequatur. Nam necessitatibus eum officia velit. Ducimus itaque natus et numquam.',
      '2013-06-26 00:43:24',
      '2013-06-26 00:43:24',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '24',
      '72',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Construction Equipment Operator',
      'Dolore laudantium non qui nam consequatur omnis autem. Itaque dolorem nihil vitae magnam labore voluptatem aliquam dolorem. Assumenda quos quibusdam nobis minima qui mollitia reprehenderit id.',
      '2012-10-06 13:19:30',
      '2012-10-06 13:19:30',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '23',
      '114',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Crossing Guard',
      'Aliquam voluptates sed aut vero et dolorem aut. Et quia veritatis facilis adipisci fugit hic pariatur dignissimos. Nostrum sit voluptates cumque. Eaque velit voluptatem exercitationem.',
      '2008-09-10 22:39:12',
      '2008-09-10 22:39:12',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '36',
      '107',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Tractor Operator',
      'Inventore ut et est esse magnam veritatis in. Quaerat quam maxime quo eius ut cupiditate omnis vitae. Suscipit adipisci enim id quidem nobis.',
      '2013-06-10 10:32:11',
      '2013-06-10 10:32:11',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '16',
      '117',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Extruding Machine Operator',
      'Dolorem iste expedita eveniet ipsa. Nesciunt doloremque aperiam neque a.',
      '2011-08-23 23:57:51',
      '2011-08-23 23:57:51',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '21',
      '104',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Central Office and PBX Installers',
      'Iste aut consectetur necessitatibus expedita consequatur nobis. Illo aperiam facere mollitia aut similique aliquam eum. Est qui placeat aliquid ut. Nemo ut id amet. Placeat nesciunt et qui tempora recusandae aut.',
      '2011-05-14 12:40:40',
      '2011-05-14 12:40:40',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '38',
      '46',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Horticultural Worker',
      'Et itaque omnis ut ex. Distinctio libero neque natus dolore adipisci nesciunt numquam aut. Enim facere cupiditate est autem in harum velit.',
      '2014-08-05 19:40:06',
      '2014-08-05 19:40:06',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '9',
      '71',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Interviewer',
      'Ut sed voluptatem quas rerum. Suscipit vero dolores accusamus saepe qui exercitationem.',
      '2016-01-25 17:56:44',
      '2016-01-25 17:56:44',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '22',
      '96',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Manager of Food Preparation',
      'Est non impedit impedit perspiciatis voluptatum repellendus omnis temporibus. Quae nihil et laudantium. Fuga est accusamus omnis deserunt. Distinctio tempore libero sequi reiciendis necessitatibus enim praesentium.',
      '2017-09-17 18:47:23',
      '2017-09-17 18:47:23',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '24',
      '117',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Plumber OR Pipefitter OR Steamfitter',
      'Velit nihil fugit odio. Sit est dolor velit molestias et ullam. Qui nam autem tempore fugit iste placeat. Nisi animi incidunt ea.',
      '2014-05-25 22:41:20',
      '2014-05-25 22:41:20',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '8',
      '77',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'CEO',
      'Culpa eum sed doloremque earum. Exercitationem sunt corrupti dolor totam hic velit veritatis. Alias itaque minus aut ab dolor nostrum fugit. Hic quia temporibus non vel pariatur et.',
      '2012-07-26 16:11:36',
      '2012-07-26 16:11:36',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '32',
      '70',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Receptionist and Information Clerk',
      'Et deleniti recusandae omnis et vitae autem ducimus. Veniam ipsum cumque inventore non vitae necessitatibus. Voluptatum autem corrupti molestiae vel. Expedita minus repellendus optio porro sint.',
      '2013-05-25 04:18:02',
      '2013-05-25 04:18:02',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '14',
      '67',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Clinical Psychologist',
      'Dolorem molestiae a saepe id necessitatibus. Voluptatem soluta maxime eos aut voluptatem. Voluptatem maiores earum qui soluta optio similique nemo. Minima est ut natus aut adipisci vel quidem. Qui aut iure facilis qui eaque commodi.',
      '2009-07-10 11:01:59',
      '2009-07-10 11:01:59',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '14',
      '100',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Shear Machine Set-Up Operator',
      'Incidunt atque expedita aut quasi reiciendis veritatis. Harum maiores nulla dolor a eligendi quia. Omnis optio amet non temporibus quia inventore sed. Ut suscipit dolorem vel expedita nesciunt fugiat deleniti.',
      '2008-02-16 13:12:45',
      '2008-02-16 13:12:45',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '26',
      '103',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Tour Guide',
      'Ex soluta enim officiis tempora neque. Quod repellendus autem et et non dolor. Unde aut molestiae voluptatem dolore asperiores cum. Aut vero officia molestias.',
      '2015-03-08 04:15:22',
      '2015-03-08 04:15:22',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '23',
      '109',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Licensing Examiner and Inspector',
      'Eum aut culpa aliquid delectus non. Aut ut optio voluptatem voluptatem. Et ut eos neque nihil beatae dolores quia itaque. Laboriosam aperiam veniam temporibus molestiae reprehenderit tempora.',
      '2009-10-24 18:34:07',
      '2009-10-24 18:34:07',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '7',
      '97',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Spotters',
      'Inventore provident tenetur perspiciatis error atque. Qui repudiandae ex consequatur velit vel. Eos nobis fuga et autem aliquid.',
      '2009-09-28 20:15:02',
      '2009-09-28 20:15:02',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '30',
      '109',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Occupational Therapist Aide',
      'Ducimus pariatur est odit repellendus molestiae est. Doloribus asperiores omnis consequatur consequatur eligendi et. Velit minima rerum cum error ut.',
      '2012-11-03 00:14:11',
      '2012-11-03 00:14:11',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '14',
      '96',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Fire Fighter',
      'Distinctio aut necessitatibus nam unde minima perferendis vel. Nam cumque esse accusamus possimus facilis et. Ut molestias et voluptatem laborum voluptatem soluta aut. Eos illum quae tempore eum.',
      '2016-05-28 07:40:50',
      '2016-05-28 07:40:50',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '24',
      '86',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Network Systems Analyst',
      'Quis dolorem fuga sed temporibus in rem. Laudantium nemo doloremque et dolorum minus debitis tenetur ullam. Laborum reprehenderit corporis ea.',
      '2012-01-07 02:29:53',
      '2012-01-07 02:29:53',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '28',
      '95',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Ship Carpenter and Joiner',
      'Rerum corporis quibusdam quaerat. Et illo vitae doloribus ut ullam quia. Ducimus porro rem voluptas sit qui.',
      '2016-03-25 09:58:50',
      '2016-03-25 09:58:50',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '24',
      '100',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Title Searcher',
      'Rem debitis sint et culpa consequatur ut. Qui voluptas maxime odio amet.',
      '2010-11-06 07:09:26',
      '2010-11-06 07:09:26',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '38',
      '89',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Refinery Operator',
      'Eveniet non cumque tempore. Quos sit optio perferendis iusto deserunt amet qui. Id consequatur ab ea aut est. Quae libero maiores perspiciatis vel et.',
      '2009-05-23 03:18:32',
      '2009-05-23 03:18:32',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '31',
      '92',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Engraver',
      'Maiores qui qui maxime quos rerum et saepe. Quidem est alias ut. Ea rerum nostrum velit soluta. Vel rem non eum aliquam harum aut expedita molestias.',
      '2012-09-19 20:16:33',
      '2012-09-19 20:16:33',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '29',
      '100',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Public Relations Specialist',
      'Similique numquam debitis dolor facere asperiores impedit. Voluptatem ipsum autem voluptatum quibusdam deserunt ex. Quidem eos blanditiis a commodi autem aut. Ut dolores voluptatem suscipit ea dolorem quis.',
      '2013-02-03 19:40:29',
      '2013-02-03 19:40:29',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '26',
      '90',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Physics Teacher',
      'Corrupti distinctio magni enim rerum voluptatem error dolores. Qui voluptatibus atque doloribus aut. Quia qui excepturi ea iusto voluptas sint dolorum occaecati.',
      '2009-12-23 14:14:45',
      '2009-12-23 14:14:45',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '29',
      '83',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Automotive Body Repairer',
      'Labore fuga eius laboriosam ab natus ipsa perspiciatis aliquid. Aut deserunt eum dolore eius sunt adipisci saepe vitae. Esse aut aspernatur perferendis similique asperiores et veniam. Voluptatum molestiae laborum sit itaque.',
      '2008-06-17 19:13:51',
      '2008-06-17 19:13:51',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '38',
      '63',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Director Of Business Development',
      'Possimus qui molestiae voluptatem. Quasi atque vel ipsam quod delectus. Aperiam qui voluptatum suscipit corrupti est. Quam iusto et sit molestiae quia eveniet facere.',
      '2013-12-05 12:06:14',
      '2013-12-05 12:06:14',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '31',
      '115',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Chemist',
      'Laudantium laudantium dolorem libero. Eum minus provident beatae aut. Earum et voluptas illo nobis ut numquam hic. Similique ut velit rerum exercitationem occaecati.',
      '2009-10-18 05:01:55',
      '2009-10-18 05:01:55',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '12',
      '93',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Precision Etcher and Engraver',
      'Nesciunt quam voluptatem ut esse. Veniam eos rerum optio voluptas aspernatur deserunt consequatur. Voluptatem non ut minima rerum officiis et et illo. Perspiciatis voluptate sit quae sed.',
      '2008-01-20 18:38:06',
      '2008-01-20 18:38:06',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '25',
      '93',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Bartender',
      'Labore ut explicabo excepturi perspiciatis. Est maxime mollitia aut. Ratione aut aut dolore et sunt. Et tempora eum est sapiente asperiores aut cumque.',
      '2008-01-09 10:14:50',
      '2008-01-09 10:14:50',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '18',
      '79',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Hydrologist',
      'Animi voluptatibus voluptatem sed aut ut cum. Blanditiis adipisci unde fugit natus reprehenderit. Aut perferendis molestias doloremque debitis tenetur est. Est incidunt perferendis commodi consequatur.',
      '2012-02-24 15:20:38',
      '2012-02-24 15:20:38',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '36',
      '84',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Photographic Developer',
      'Dolor et architecto assumenda corrupti dicta aliquid. Reprehenderit natus rerum iure. Facilis earum et nostrum quidem eum inventore.',
      '2011-08-29 02:02:32',
      '2011-08-29 02:02:32',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '37',
      '90',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Geographer',
      'Et sed est nam velit fugiat impedit. Vel velit ipsa molestiae mollitia doloribus dolorem et tempora. Ut natus ut nesciunt et ipsum eum. Velit quia officia tenetur consequuntur dignissimos exercitationem quaerat.',
      '2011-10-09 12:18:27',
      '2011-10-09 12:18:27',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '7',
      '69',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Career Counselor',
      'Veritatis accusantium officiis id quo corporis. Enim voluptatem temporibus consequatur et aperiam sunt natus. Maiores sapiente cumque temporibus fuga natus. Ab quas amet voluptatem. Quia molestiae quidem omnis non vel necessitatibus.',
      '2016-11-10 23:11:49',
      '2016-11-10 23:11:49',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '5',
      '90',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Amusement Attendant',
      'Unde saepe ea voluptate consequatur nihil accusamus sequi. Rerum soluta in doloremque dolorem voluptatum adipisci. Sequi facilis pariatur unde voluptates porro temporibus. Quod nihil ipsa dolores unde est.',
      '2017-03-04 23:05:53',
      '2017-03-04 23:05:53',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '24',
      '57',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Occupational Therapist Assistant',
      'Id eos quo qui sapiente. Voluptas aut est et unde voluptatem. Consequatur id numquam consequatur.',
      '2014-08-19 07:19:04',
      '2014-08-19 07:19:04',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '35',
      '119',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Machine Feeder',
      'Blanditiis veniam officia aut a. In impedit qui molestias omnis. Dolorem exercitationem nesciunt excepturi minima a. Porro est et aut quod ut expedita repellat.',
      '2016-05-12 02:18:16',
      '2016-05-12 02:18:16',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '32',
      '108',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Municipal Fire Fighting Supervisor',
      'Sit sequi dolore labore voluptas consequuntur dicta expedita nulla. Dolor reprehenderit illum et iusto. Qui incidunt facilis nisi. Incidunt et qui corporis libero. Expedita quaerat iusto voluptas expedita.',
      '2014-05-06 09:07:20',
      '2014-05-06 09:07:20',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '13',
      '78',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Personal Care Worker',
      'Et voluptas eveniet facere accusantium recusandae sed possimus. Officia reiciendis ipsam est aperiam.',
      '2014-01-25 07:53:56',
      '2014-01-25 07:53:56',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '10',
      '118',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Custom Tailor',
      'Praesentium perferendis cumque a eos omnis fugit sequi laboriosam. Quo nisi tempora commodi pariatur. Recusandae sapiente autem soluta qui. Iure officiis aut architecto ut corrupti.',
      '2009-07-07 11:57:07',
      '2009-07-07 11:57:07',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '18',
      '113',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Human Resource Manager',
      'Dolor consectetur rerum ad. Doloremque non fugit perferendis facilis recusandae. Quidem iure veniam asperiores ea sed alias. Distinctio voluptates necessitatibus enim aut suscipit quaerat.',
      '2013-11-11 03:39:11',
      '2013-11-11 03:39:11',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '22',
      '91',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Loan Interviewer',
      'Est est eos corrupti asperiores quis sunt minus. Quia incidunt rerum repudiandae aliquam quod deserunt. Et aspernatur excepturi velit quod eaque. Rerum aut sunt quibusdam autem sequi accusantium est mollitia. Natus voluptate sit consectetur eos beatae voluptas debitis.',
      '2016-10-01 05:56:32',
      '2016-10-01 05:56:32',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '9',
      '112',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Woodworking Machine Setter',
      'Veniam ullam qui nam consequatur eveniet odio quae facilis. Accusantium non doloremque eius consequatur. Id et quo ut est ut tempora repellendus cumque. Non sint saepe ullam earum quisquam temporibus ad. Sit est saepe officia tenetur incidunt qui praesentium.',
      '2009-06-23 16:56:14',
      '2009-06-23 16:56:14',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '35',
      '92',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Painter and Illustrator',
      'Velit omnis perspiciatis totam cupiditate eos. Earum distinctio temporibus libero eligendi. Repudiandae eum magnam accusamus debitis qui quidem.',
      '2008-01-30 01:10:18',
      '2008-01-30 01:10:18',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '9',
      '104',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Engineering Teacher',
      'Provident odio ut dolor minus molestias qui iure. In et expedita recusandae voluptatem eum. Numquam qui perspiciatis aperiam excepturi aut mollitia. Sapiente impedit quisquam odit enim voluptatibus quas quibusdam.',
      '2017-04-04 22:58:17',
      '2017-04-04 22:58:17',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '33',
      '96',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Administrative Services Manager',
      'Recusandae voluptates accusamus consequuntur consequuntur sit dolorem eaque excepturi. Aut quia ratione totam distinctio autem quia quia. Est ipsam cumque ea non totam vitae. Quas nihil velit laudantium voluptatum consequatur.',
      '2014-07-01 21:34:10',
      '2014-07-01 21:34:10',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '33',
      '68',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Fashion Model',
      'Natus qui cumque quisquam sit. Fugiat est illum autem soluta.',
      '2010-11-12 21:07:58',
      '2010-11-12 21:07:58',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '27',
      '73',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Rigger',
      'Ut adipisci saepe consequatur tempore facilis. Pariatur aliquid temporibus enim quo. Possimus eum voluptas sed cupiditate accusantium.',
      '2013-05-12 01:01:51',
      '2013-05-12 01:01:51',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '29',
      '72',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Steel Worker',
      'Veritatis minima est maiores quaerat quis quis voluptatem. Eligendi est non et voluptatem consequatur fugit. Non sed consectetur adipisci et possimus a. Est odio qui temporibus quo iste aut.',
      '2011-02-05 07:06:31',
      '2011-02-05 07:06:31',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '24',
      '95',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Online Marketing Analyst',
      'Nemo alias cumque soluta repudiandae ut a eveniet. Ratione eius recusandae qui. Porro beatae sunt eligendi deleniti eaque saepe veritatis quos.',
      '2015-05-01 01:21:50',
      '2015-05-01 01:21:50',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '36',
      '89',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Metal Worker',
      'Modi cumque ut beatae voluptatem porro. Animi laborum dolor veritatis quia aspernatur. Doloremque error laboriosam et qui. Dolorum aliquid harum autem eveniet.',
      '2015-02-13 05:49:02',
      '2015-02-13 05:49:02',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '27',
      '108',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'School Bus Driver',
      'Ipsa commodi culpa at quis sit nostrum sint. Incidunt natus eum nobis sed ut totam itaque. Numquam quis aut qui repellat ab repellendus aut.',
      '2017-03-14 12:01:44',
      '2017-03-14 12:01:44',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '27',
      '85',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Director Of Talent Acquisition',
      'Vitae quos id et error. Aperiam velit incidunt est maiores qui quae odit. Sunt magnam porro voluptatem alias vitae.',
      '2015-08-04 21:47:06',
      '2015-08-04 21:47:06',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '36',
      '105',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'First-Line Supervisor-Manager of Landscaping, Lawn Service, and Groundskeeping Worker',
      'Sequi quisquam sed corrupti eligendi deleniti quo veritatis. Eaque quia culpa unde delectus occaecati unde tempore veritatis. Consequatur velit reiciendis magni occaecati fugiat doloremque. Magnam exercitationem reprehenderit culpa aliquid dolore repudiandae.',
      '2016-12-23 05:09:00',
      '2016-12-23 05:09:00',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '15',
      '81',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Transportation Manager',
      'Ipsum illum labore voluptatibus dolores aut. In laboriosam qui vel ut quasi modi aut beatae.',
      '2008-07-13 11:34:43',
      '2008-07-13 11:34:43',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '20',
      '108',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Database Manager',
      'Non accusantium cupiditate nihil maxime incidunt ut. Eos quisquam qui ipsum libero aut. Et quia ut qui est tenetur vitae reprehenderit.',
      '2008-05-10 21:22:37',
      '2008-05-10 21:22:37',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '24',
      '60',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Photographic Reproduction Technician',
      'Ad eum dolorem beatae temporibus. Neque voluptatem dolorem consequatur eius eaque. Laboriosam unde aut et eum. Neque a minus dolorum est voluptatem earum.',
      '2013-09-25 09:39:13',
      '2013-09-25 09:39:13',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '25',
      '106',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Political Science Teacher',
      'Aperiam unde nulla quasi dignissimos rem voluptatem quam odio. Repudiandae omnis omnis aspernatur minima doloribus numquam. Veniam quia nobis repellat.',
      '2008-06-28 15:38:06',
      '2008-06-28 15:38:06',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '29',
      '94',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Diamond Worker',
      'Quos aut in et. Accusantium qui magni commodi ad maxime qui illo. Illum aspernatur totam doloribus laborum ut quaerat incidunt.',
      '2017-08-08 03:02:35',
      '2017-08-08 03:02:35',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '22',
      '60',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Gaming Service Worker',
      'Praesentium perferendis iusto sequi temporibus ut fugit quia. Blanditiis provident a sapiente optio occaecati. Eos et est hic.',
      '2009-07-26 01:16:57',
      '2009-07-26 01:16:57',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '27',
      '107',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Welder',
      'Quibusdam aut necessitatibus rerum debitis. Esse explicabo porro iste officia ipsum vitae consectetur. Expedita dignissimos est illum officia dolores nihil dolorem.',
      '2008-04-07 04:21:42',
      '2008-04-07 04:21:42',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '7',
      '106',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Transportation and Material-Moving',
      'Quasi voluptatem ipsum voluptatum reiciendis cupiditate et. Voluptatum recusandae vel qui recusandae officia consequatur. Ut perspiciatis dolores ducimus accusantium laboriosam. Modi facere alias consequatur accusamus dolor.',
      '2014-06-04 10:43:42',
      '2014-06-04 10:43:42',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '28',
      '99',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Loan Officer',
      'Optio in facilis nihil maiores nulla itaque. Et eum est facere culpa velit dolorem et. Voluptatem quo est dolorem dolor commodi possimus. Ratione odit eveniet ullam reiciendis ullam ipsum veritatis. Et voluptas officia enim.',
      '2011-03-23 04:43:25',
      '2011-03-23 04:43:25',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '7',
      '108',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Food Science Technician',
      'Itaque quae eum ut sequi. Quis recusandae ullam sit placeat. Ea quae et magni et blanditiis ullam.',
      '2009-10-20 11:16:57',
      '2009-10-20 11:16:57',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '34',
      '60',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'MARCOM Director',
      'Aspernatur incidunt minima quo voluptas molestiae cumque modi. Sapiente beatae earum facilis. Voluptatem velit et dicta sit rerum qui. Officiis aperiam provident nam porro tempora voluptas neque qui.',
      '2009-09-25 23:20:50',
      '2009-09-25 23:20:50',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '5',
      '89',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Pharmaceutical Sales Representative',
      'Rerum omnis molestias laboriosam rerum libero qui repellendus. Perferendis id harum repellendus labore eius perferendis dicta sed. Ea laboriosam aut vero.',
      '2016-01-20 19:42:38',
      '2016-01-20 19:42:38',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '30',
      '102',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Mathematical Scientist',
      'Libero rem voluptates est consequatur. Possimus sint tempore suscipit esse deserunt. Omnis saepe accusamus optio quaerat aliquam vel. Eligendi dolores a doloribus ad ea.',
      '2012-07-14 10:58:09',
      '2012-07-14 10:58:09',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '21',
      '93',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Costume Attendant',
      'Error consequatur hic fuga sequi. Voluptatum et iusto voluptatibus rerum et accusantium. Ea cupiditate consequatur quo libero. Repudiandae atque et non debitis.',
      '2015-02-15 04:12:46',
      '2015-02-15 04:12:46',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '9',
      '85',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Secretary',
      'Quaerat velit sed voluptates et neque nostrum. Atque sunt sint dolores reiciendis adipisci odio. Incidunt amet nostrum rerum non. Quos repellendus quia in qui qui.',
      '2017-09-08 00:50:39',
      '2017-09-08 00:50:39',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '23',
      '104',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Online Marketing Analyst',
      'Sit maiores dicta hic incidunt pariatur nostrum vel. Autem aspernatur et nulla aut autem. Voluptatem exercitationem odit repellendus reprehenderit nihil. Ut illum et dolorem nobis recusandae.',
      '2009-09-18 13:01:00',
      '2009-09-18 13:01:00',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '14',
      '100',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Cashier',
      'Omnis eos eaque culpa reiciendis fugiat voluptatem quo. Earum omnis est expedita asperiores voluptatum. Quia voluptas voluptatem et dolorum rerum voluptas ut. Id suscipit quia autem rem velit.',
      '2011-07-03 18:44:28',
      '2011-07-03 18:44:28',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '37',
      '107',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Internist',
      'Cum repellendus sed labore temporibus facere officiis inventore. Velit non autem non.',
      '2009-12-30 06:18:48',
      '2009-12-30 06:18:48',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '30',
      '108',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Pharmaceutical Sales Representative',
      'Velit vel odit sint nobis repellendus adipisci consequatur. Et maxime placeat laudantium voluptatibus nihil aut est. Enim voluptas voluptatem sed eveniet quis. Voluptas enim ut iure possimus soluta.',
      '2011-06-02 13:37:00',
      '2011-06-02 13:37:00',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '21',
      '100',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Shampooer',
      'Consequatur sit esse id ducimus ut aut debitis aut. Qui repellat aut officia dolore ut. Rerum vel facilis aut laboriosam modi vel rerum dolorem.',
      '2015-01-21 10:58:22',
      '2015-01-21 10:58:22',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '31',
      '90',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Food Scientists and Technologist',
      'Id reprehenderit aut molestiae minus nesciunt esse neque blanditiis. Tempora rem autem fuga doloribus cupiditate enim odio. Ullam quisquam nisi minus qui hic illum.',
      '2012-12-09 10:08:22',
      '2012-12-09 10:08:22',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '7',
      '73',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Signal Repairer OR Track Switch Repairer',
      'Voluptatem ducimus at praesentium et possimus. Aut voluptatibus nostrum libero libero quaerat qui ratione. Ipsa quod totam veniam est quo est dolores. Deserunt autem et numquam repellendus fuga.',
      '2016-07-14 12:56:16',
      '2016-07-14 12:56:16',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '34',
      '116',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Occupational Health Safety Specialist',
      'Aliquid facilis tempore nam amet magni rem. Quisquam sed esse laborum modi reprehenderit voluptatem. Ratione aut illo ad perspiciatis. Iste ut odit dolorum suscipit.',
      '2013-04-08 16:52:16',
      '2013-04-08 16:52:16',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '33',
      '109',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Welder',
      'Inventore ut natus qui quo officiis. Sunt aperiam et id omnis qui voluptas nihil doloribus. Quibusdam veniam est vitae.',
      '2009-08-01 18:14:25',
      '2009-08-01 18:14:25',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '29',
      '79',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Electronics Engineering Technician',
      'Sit aspernatur beatae consequatur. Dolores nesciunt in tempora non dicta. Tempora aut rerum qui modi. Eius perferendis voluptas omnis tenetur aut provident.',
      '2009-11-26 13:13:49',
      '2009-11-26 13:13:49',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '34',
      '67',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);