INSERT INTO `mini`.`Task` (
    `title`,
    `description`,
    `created_at`,
    `updated_at`,
    `start_at`,
    `end_at`,
    `min_bid`,
    `max_bid`,
    `creator_username`,
    `assignee_username`,
    `deleted_at`,
    `creator_rating`,
    `assignee_rating`,
    `completed_at`,
    `remarks`)
    VALUES (
      'Loan Counselor',
      'Illo et vel ipsum totam. Fuga fugit consequatur sunt ut. Modi iure magni cum suscipit earum sapiente. Voluptatibus reiciendis optio soluta aut. Vero facere et est dolore.',
      '2008-06-09 08:06:12',
      '2008-06-09 08:06:12',
      '2017-10-16 00:00:00',
      '2017-10-21 00:00:00',
      '13',
      '94',
      'asdfasf',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL);